# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'

- task: DotNetCoreCLI@2
  inputs:
    command: restore

- task: DotNetCoreCLI@0
  inputs:
    command: build

- task: DotNetCoreCLI@2
  inputs:
    command: test

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true
